export default {
    ADD_MESSAGE: 'SHOW_MESSAGE',
    HIDE_MESSAGE: 'HIDE_MESSAGE',
    INITIALIZE_COMPONENT_TOASTER: 'INITIALIZE_COMPONENT_TOASTER',
    DEINITIALIZE_COMPONENT_TOASTER: 'DEINITIALIZE_COMPONENT_TOASTER'
};
